# Generated by Django 4.0.6 on 2022-08-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_category', models.CharField(choices=[('AC', 'AC'), ('NAC', 'Non-AC'), ('DEL', 'DELUX'), ('KIN', 'KING'), ('QUE', 'QUEEN')], default='AC', max_length=3)),
                ('bed_category', models.CharField(choices=[('SI', 'Single Bed'), ('DB', 'Double Bed'), ('KS', 'King Size'), ('QN', 'Queen Size'), ('FM', 'Family Room')], default='DB', max_length=2)),
                ('capacity', models.IntegerField()),
                ('wifi', models.BooleanField(default=True)),
                ('tv', models.BooleanField(default=True)),
                ('food', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='room_photos/')),
            ],
            options={
                'verbose_name': 'Rooms',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
