# Generated by Django 4.0.6 on 2022-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Rooms', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ImageField(null=True, upload_to='room_photos/'),
        ),
    ]
